### ISSUE TITLE
ImportError: No module named 'RPi'

### ISSUE THREAD

**Issue by wes1007** [sourceperl/rpi.rtc#4]
after running:
`sudo python3 setup.py install`

and then running 
`ds1302_get_utc`

I get:

> Traceback (most recent call last):
>   File "/usr/local/bin/ds1302_get_utc", line 4, in <module>
>     __import__('pkg_resources').run_script('pyRPiRTC==0.0.3', 'ds1302_get_utc')
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/local/lib/python3.5/dist-packages/pyRPiRTC-0.0.3-py3.5.egg/EGG-INFO/scripts/ds1302_get_utc", line 7, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/pyRPiRTC-0.0.3-py3.5.egg/pyRPiRTC.py", line 3, in <module>
> ImportError: No module named 'RPi'

I am running Raspbian Stretch Lite 2018-11-13 on a PI3 B+

**Comment by sourceperl** [comment]
try:
`sudo apt-get -y install python3-rpi.gpio`

**Comment by wes1007** [comment]
Thanks a mil. working now. Hopefully someone else with a similar issue will come across this.
